# Generated by Django 2.2.9 on 2021-02-13 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210213_2035'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='group_fk',
            new_name='group',
        ),
        migrations.AlterField(
            model_name='group',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
